### ISSUE TITLE
list index out of range

### ISSUE THREAD

**Issue by alek0991** [ngarud/SelectionHapStats#1]
Hi, 
I'm trying to run `H12_H2H1.py` but It usually raises this error:

>   File "../scripts/H12_H2H1.py", line 77, in clusterHaplotypes
>     flies[j].append(linecache.getline(inFile,center + window +i).split(',')[j].strip())
> IndexError: list index out of range

I looked into the code and it seems for the window represented by the value of the variable `center`, line indices are like this (define `c = center` and `w = window`): 

> [c-w, c-w+1, ..., c-1, c, c+1, ..., c+w-jump-1, c+w-jump, c+w, c+w+1, ..., c+w+jump-1 ] 

While it's expected to be like this:

> [c-w, c-w+1, ..., c-1, c, c+1, ..., c+w-1, c+w ] 

https://github.com/ngarud/SelectionHapStats/blob/696860b30b8107f33d0fb9e7e452b099fe31b936/scripts/H12_H2H1.py#L75-L77

In line 77, changing  `center + window +i` to `center + window + i - jump + 1` will fix this issue. Otherwise it never calls lines `[2w+2,..., 2w+jump] ` and calls incorrect lines (that sometimes don't exist) and consequently raise the error 'list index out of range'. 

I changed the code like this: 
```
            for i in range(0,jump):
                lll = linecache.getline(inFile, center + window + i - jump + 1).split(',')
                for j in range(1,numStrains+1):
                    # flies[j].append(linecache.getline(inFile,center + window +i).split(',')[j].strip())
                    flies[j].append(lll[j].strip())
```
By moving the  `linecache.getline()` to the first loop you can get ~10x speed up. The same goes for calling the `linecache.getline()` in `initialize()`.
 
Am I right?
 Please let me know if I'm missing something. 
Thank you, 
Ali

**Comment by ngarud** [comment]
Hi! Thanks for the comment. I think you are right -- I actually had this fix that you recomemended in an earlier version of my code. I have fixed this. 
Thanks for pointing out the speedup!

**Comment by alek0991** [comment]
Many thanks for the prompt response.

**Comment by alek0991** [comment]
Many thanks for the prompt response.

**Comment by C-grapes** [comment]
> Hi! Thanks for the comment. I think you are right -- I actually had this fix that you recomemended in an earlier version of my code. I have fixed this. Thanks for pointing out the speedup!

Hi! I use the test data test_MLG_data.txt you provided and the script H12_H2H1.py to calculate G12, but I always get this error: IndexError: list index out of range. The command I used is also provided in the manual: python H12_H2H1.py test_MLG_data.txt 145 –o test_MLG_output_200_50.txt –w 200 –j 50 –d 0. Can you help me with this problem? In addition, I have successfully calculated H12, but I always get an error when calculating G12.

**Comment by kuangzhuoran** [comment]
Hi!
I met another “list index out of range” at Line 129。
It's the same when using the example file.。

at line 125-129:
    # Add SNPs to the left and the right
    for i in range(0,window+1):
        #left
        for j in range(1,numStrains+1):
            flies[j].append(linecache.getline(inFile,center-window +i).split(',')[j].strip())



$ python scripts/H12_H2H1.py nput.txt 32 -o output.txt
Traceback (most recent call last):
  File "scripts/H12_H2H1.py", line 414, in <module>
    main()
  File "scripts/H12_H2H1.py", line 408, in main
    clusterHaplotypes(inFile, outFile, windowTot, jump, distanceThreshold, numStrains)
  File "scripts/H12_H2H1.py", line 59, in clusterHaplotypes
    flies = initialize(window, center, inFile)
  File "scripts/H12_H2H1.py", line 129, in initialize
    flies[j].append(linecache.getline(inFile,center-window +i).split(',')[j].strip())
IndexError: list index out of range

**Comment by kuangzhuoran** [comment]
It might be because the number of SNPs in the example file is too small. When I used data from a complete chromosome, there were no errors.
