### ISSUE TITLE
Building/understanding input files

### ISSUE THREAD

**Issue by tomoosting** [ngarud/SelectionHapStats#3]
Hi,

I've been going over the documentation that explains the input file format, but I'm having trouble understanding how the program reads heterozygous sites for the H12 analyses. For example:

Phased data: 3948,A,A,A,N,T,A,A,A,T,…etc
Unphased data: 3948,A,.,.,N,T,.,A,.,T,…etc 

How does the program know that individual 2 and 3 the sites are Heterozygous when only one allele is given?
I thought that maybe all heterozygous sites were converted to N, however that wouldn't work with the example from the unphased data.
I'm ultimately interested in using the G12 statistic but would like to fully understand how the data files are being read.

I was also wondering if you have any advice/scripts that help convert conventional calling formats (e.g. plink, vcf, ...) to the required input file.

Many thanks!

**Comment by ngarud** [comment]
Hi Tom,

The period ('.') indicates a heterozygous site.

My colleague, Arbel Harpak, wrote a script to convert VCF to the input
format for the H12 code. Please cite him if you use the code. I don't have
any further documentation to provide.

Thanks,
Nandita

**Comment by tomoosting** [comment]
Hi Nandita,

Thank you for the quick reply.

So I understood that the '.' indicates a heterozygous site.
It's just not clear to me how the respective sites for the phased data (H12) are read as heterozygous.
In the example they are indicated as a single nucleotide, and as far as I can tell indistinguishable from homozygous sites.
So how does the program read heterozygous sites for phased data?

I tried to find any documentation on the script Arbel Harpak wrote.
But I can't find anything on his personal page, github or supplementary information from any of the associated publications.
Is there an official source for the script that I can then cite, or would I have to reach out to him personally?

Best,
Tom

**Comment by ngarud** [comment]
Hi Tom

If you have phased data, then by definition you cannot have a heterozygous
site.

You are welcome to contact Arbel, I do not have any further documentation.
It's really just provided to you for your convenience.

Nandita

**Comment by tomoosting** [comment]
Hi Nandita,

Clearly I haven't worked with phased data..
I'll have to wrap my head around that.
Thank you for taking the time to respond.

Best,
Tom
