### ISSUE TITLE
Input file generation for G12

### ISSUE THREAD

**Issue by g-fabbri** [ngarud/SelectionHapStats#5]
Hello! I was wondering if there is a convenient way to get the input file format required for G12. I can start from a vcf, I have ~8M SNPs over 18 autosomal chromosomes.
Thank you for any suggestion!

Giulia

**Comment by timurrxxcd** [comment]
hello did you solve the problem? I'm facing the same issue

**Comment by g-fabbri** [comment]
Hi! Yes I made a script for the conversion from unphased data. I'll leave it here in case it can be useful, it's certainly not very efficient but it works fine :)
Basically I start from one file per chromosome, with only one population and no invariant sites, then I save in the variables $ref and $alt the reference and alternative allele for each site and I write the corresponding letter saved in $ref when there is 0/0 or 0|0 or the letter saved in $alt when there is 1/1 or 1|1, while if the site is heterozygote I write "." and if it's missing I write "N". 
Don't compress the text file you obtained like this because the scripts to compute G12 don't handle gzipped files for what I experienced.

zgrep -v ^# ${POP}_${BN}_${N}.vcf.gz | while read line
do 
 ref=$(echo $line | awk '{print $4}') 
 alt=$(echo $line | awk '{print $5}')
 echo $line | sed -r "s/0(\/|\|)0/$ref/g ; s/1(\/|\|)1/$alt/g ; s/0(\/|\|)1/./g ; s/1(\/|\|)0/./g ; s/.(\/|\|)./N/g" | cut -d' ' --output-delimiter="," -f2,10-
done >> ${POP}_${BN}_${N}.txt

**Comment by timurrxxcd** [comment]
this is for unphased data, right? but do you think it works for phased data also? my data structure is attached in the picture
![Capture](https://github.com/ngarud/SelectionHapStats/assets/86943771/c7871b87-4b06-49d1-b3f9-3466c75fc3ab)

**Comment by g-fabbri** [comment]
Yes absolutely it works on your data structure too. I just noticed that I don't know why github is formatting the script differently in the series of sed commands so I'm going to attach it as a text file
[g12_data_prep.txt](https://github.com/user-attachments/files/16053030/g12_data_prep.txt)

**Comment by timurrxxcd** [comment]
I see, this code works for unphased data 100%. but I need to modify it for phased data (as my data is phased). But, I don't know how I do :(. It's ok, thanks for sharing the script

**Comment by g-fabbri** [comment]
No it works already for phased data too because in the sed command I have already written to look for genotypes separated both by "/" (unphased) and by "|" (phased).

**Comment by timurrxxcd** [comment]
oh, really? then let me test it. Then I will send the result

**Comment by timurrxxcd** [comment]
@g-fabbri I used the same script you provided. However, I have dots in the data as seen in the picture below. But my data was inputed and phased. how this can happen? maybe, in the code, did you use replace function, that heterozygous sites must be replaced by dots? as suggested in the manual of SelectionHapStats for unphased data? 
![image](https://github.com/ngarud/SelectionHapStats/assets/86943771/bf43b28a-ed05-4f19-89d4-f641ae37f1e7)

**Comment by timurrxxcd** [comment]
I ran the code provided in the manual. But I'm getting error which I couldn't understand. 
![image](https://github.com/ngarud/SelectionHapStats/assets/86943771/55ecd4ed-49de-4121-a961-bca04df8e74a)
![image](https://github.com/ngarud/SelectionHapStats/assets/86943771/230d56c4-90fb-49b8-8717-707c954b8ff5)

**Comment by g-fabbri** [comment]
You need to run it with python 2.X, I got the same error when I loaded python 3.X on my cluster.

**Comment by timurrxxcd** [comment]
Yes I ran it successfully thanks for help brother

**Comment by g-fabbri** [comment]
no problem :)

**Comment by kuangzhuoran** [comment]
Hi ! I wrote a Perl script using ChatGPT that can convert VCF to input file, based on your script. 
perl 1.vcf2input.pl input.vcf output.txt


[1.vcf2input.pl.txt](https://github.com/user-attachments/files/18227376/1.vcf2input.pl.txt)
